# PostgreSQL Database Settings
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/employee_db
db.username=postgres
db.password=postgres
db.dialect=org.hibernate.dialect.PostgreSQL9Dialect
